### ISSUE TITLE
No Makefile etc

### ISSUE THREAD

**Issue by MajickTek** [Hopson97/SFML-Game-Framework#1]
A makefile or similar will be necessary for people not using IDE's

**Comment by MajickTek** [comment]
Or at least some build instructions

**Comment by MajickTek** [comment]
Alright. This issue can be closed. You’ve added a build system.

**Comment by Hopson97** [comment]
IIRC I tried to make it work but I was unable to, due to my lack of knowledge with CMake

**Comment by Hopson97** [comment]
I'll need to make sure it actually works before closing :)
