### ISSUE TITLE
GUI stuff doesn't work with new versions

### ISSUE THREAD

**Issue by PyroFlareX** [Hopson97/SFML-Game-Framework#3]
I attempted to use/edit this framework for my own purposes, and when I tested it with SFML 2.5.0, it wouldn't compile properly because of sfml text functions. Even when commented out, it still cited more and more errors.

**Comment by Hopson97** [comment]
which functions?

**Comment by PyroFlareX** [comment]
The sf::text ones to do with font and outline size and such

i'll put errors when i get the chance

**Comment by 48cf** [comment]
Yeah, built successfully on MSVC++ 14.1 with latest Windows 10 SDK. Used SFML 2.5.0 - no errors. Everything works as supposed.
![image](https://user-images.githubusercontent.com/32851089/42973992-c65447c2-8bb5-11e8-8564-9cea40452fad.png)

**Comment by PyroFlareX** [comment]
Did some debug, idk what was wrong.
